### PR TITLE
Extend features

### PR DESCRIPTION
**Pull request by marouabahri**
Update features by adding anomaly score and duplicate will be considered in the SEDIMARK project.
The examples have been changed accordingly.
Update CONTRIBUTORS.yaml also

### CODE REVIEW

**Review by albertoabellagarcia — CHANGES_REQUESTED** [review]
Ok to the outlierScore attribute. 
How can you justify to create an object, duplicate with only one attribute inside, isDuplicate. Shouldn't be simpler to use just a boolean attribute? 
Finally, you only need to make changes in the schema.json and in the examples jsonXX the csv are generated automatically (like the specs and the rest of exports)

**Comment by marouabahri** [comment]
Hi Alberto, 
Actually, the duplicate will contain isDuplicate and foundMatches, which refers to whether isDuplicate is true and what rows it matches. It should be a list, I wasn't sure about the type of foundMatches.

**Comment by albertoabellagarcia** [comment]
Including foundmatches in the object duplicate makes sense but this is not included in the examples or in the changed schema. Glad to receive a commit with that. 
Thanks

**Review by albertoabellagarcia — CHANGES_REQUESTED** [review]
Examples should cover the extension of the schema (specifically values for the attributes isDuplicated)

**Review by albertoabellagarcia — APPROVED** [review]
will change the schema version

**Review by albertoabellagarcia — APPROVED** [review]
approved the extension

**Pull request merged**
